(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const money = n => '$' + Number(n).toFixed(2);
  const PRODUCTS = [
    {id:1,name:'Cloud-soft Onesie',category:'Onesies',price:22,stock:14,icon:'👕',color:'#e6ecdf',tag:'BEST LOVED'},
    {id:2,name:'Bunny Hug Blanket',category:'Blankets',price:34,stock:8,icon:'🧸',color:'#f2e4d9',tag:'SOFT & SNUG'},
    {id:3,name:'Little Sunshine Set',category:'Outfits',price:38,stock:6,icon:'🌼',color:'#f1ead4',tag:'NEW IN'},
    {id:4,name:'Tiny Toes Booties',category:'Accessories',price:16,stock:21,icon:'🧦',color:'#e9e5ee',tag:''},
    {id:5,name:'Dreamy Day Romper',category:'Outfits',price:29,stock:11,icon:'🩱',color:'#e5edf0',tag:''},
    {id:6,name:'Sweet Pea Beanie',category:'Accessories',price:18,stock:9,icon:'🧢',color:'#f0e5e5',tag:'HANDMADE'},
    {id:7,name:'Cuddle Cloud Muslin',category:'Blankets',price:26,stock:13,icon:'☁️',color:'#e9ece5',tag:''},
    {id:8,name:'First Hello Gift Box',category:'Gifts',price:54,stock:4,icon:'🎁',color:'#f0e4d4',tag:'GIFT READY'},
    {id:9,name:'Little Star Bodysuit',category:'Onesies',price:24,stock:17,icon:'⭐',color:'#e8e7db',tag:''}
  ];
  const KEY={users:'caytons.users.v1',orders:'caytons.orders.v1',stock:'caytons.stock.v1'};
  let users=read(KEY.users,[]), orders=read(KEY.orders,[]), stock=read(KEY.stock,Object.fromEntries(PRODUCTS.map(p=>[p.id,p.stock])));
  let cart={},category='All',signup=false,currentUser=null,faceMode='login',stream=null,human=null,discount=0,paymentMethod='Card';
  function read(k,fallback){try{const v=JSON.parse(localStorage.getItem(k));return v??fallback}catch{return fallback}}
  function persist(){localStorage.setItem(KEY.users,JSON.stringify(users));localStorage.setItem(KEY.orders,JSON.stringify(orders));localStorage.setItem(KEY.stock,JSON.stringify(stock))}
  async function hash(text){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
  function message(text){$('authMessage').textContent=text}
  function showAuth(){currentUser=null;$('appScreen').hidden=true;$('authScreen').hidden=false}
  function showApp(user){currentUser=user;$('userName').textContent=user.name||user.email.split('@')[0];$('avatar').textContent=(user.name||user.email)[0].toUpperCase();$('authScreen').hidden=true;$('appScreen').hidden=false;updateClock();renderCategories();renderProducts();renderCart();renderInventory();renderOrders()}
  function setSignup(value){signup=value;$('authTitle').textContent=signup?'Create your account':'Welcome back';$('authSubtitle').textContent=signup?'A lovely little shop starts here.':'Sign in to open your point of sale.';$('nameField').hidden=!signup;$('nameField').required=signup;$('passwordField').autocomplete=signup?'new-password':'current-password';$('authSubmit').innerHTML=signup?'Create account <span>→</span>':'Sign in <span>→</span>';$('switchText').textContent=signup?'Already have an account?':"New to Cayton's?";$('switchMode').textContent=signup?'Sign in':'Create an account';message('')}
  $('switchMode').onclick=()=>setSignup(!signup);
  $('togglePassword').onclick=()=>{const input=$('passwordField');input.type=input.type==='password'?'text':'password';$('togglePassword').textContent=input.type==='password'?'Show':'Hide'};
  $('authForm').addEventListener('submit',async e=>{e.preventDefault();message('');const email=$('emailField').value.trim().toLowerCase(),password=$('passwordField').value;
    if(signup){if(users.some(u=>u.email===email)){message('An account with this email already exists.');return}if(password.length<4){message('Please choose a password with at least 4 characters.');return}const user={id:crypto.randomUUID(),name:$('nameField').value.trim(),email,passwordHash:await hash(password)};users.push(user);persist();showApp(user);setTimeout(()=>{if(confirm('Would you like to set up optional facial recognition on this device?'))openCamera('enroll')},100);toast('Your little shop is ready!')}
    else{const user=users.find(u=>u.email===email);if(!user||user.passwordHash!==await hash(password)){message('That email and password combination was not found.');return}showApp(user);toast('Welcome back, '+(user.name||'friend')+'!')}
  });
  function categories(){return ['All',...new Set(PRODUCTS.map(p=>p.category))]}
  function renderCategories(){$('categoryRow').innerHTML=categories().map(c=>`<button class="category-pill ${category===c?'active':''}" data-category="${c}">${c}</button>`).join('');$('categoryRow').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategories();renderProducts()})}
  function renderProducts(){const query=$('searchInput').value.trim().toLowerCase(),items=PRODUCTS.filter(p=>(category==='All'||p.category===category)&&(!query||p.name.toLowerCase().includes(query)||p.category.toLowerCase().includes(query)));$('productCount').textContent=PRODUCTS.filter(p=>stock[p.id]>0).length;
    $('productGrid').innerHTML=items.length?items.map(p=>`<article class="product-card" data-product="${p.id}" ${stock[p.id]<=0?'style="opacity:.5"':''}><div class="product-art" style="background:${p.color}"><span>${p.icon}</span>${p.tag?`<span class="tag">${p.tag}</span>`:''}</div><div class="product-info"><h3>${p.name}</h3><p><span>${p.category} · ${stock[p.id]} left</span><b>${money(p.price)}</b></p></div></article>`).join():'<p class="message">No little treasures found. Try another search.</p>';
    $('productGrid').querySelectorAll('.product-card').forEach(el=>el.onclick=()=>addToCart(Number(el.dataset.product)))
  }
  function addToCart(id){if((cart[id]||0)>=stock[id]){toast('That item is out of stock.');return}cart[id]=(cart[id]||0)+1;renderCart()}
  function totals(){let subtotal=Object.entries(cart).reduce((s,[id,q])=>s+PRODUCTS.find(p=>p.id===Number(id)).price*q,0);subtotal=Math.max(0,subtotal-discount);return{subtotal,tax:subtotal*.08,total:subtotal*1.08}}
  function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);$('cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===Number(id));return `<div class="cart-item"><div class="cart-item-art" style="background:${p.color}">${p.icon}</div><div><div class="cart-item-name">${p.name}</div><div class="cart-item-price">${money(p.price)} each</div><div class="quantity"><button data-qty="${id}" data-step="-1" aria-label="Remove one">−</button><span>${q}</span><button data-qty="${id}" data-step="1" aria-label="Add one">+</button></div></div><span class="cart-item-total">${money(p.price*q)}</span></div>`}).join(''):'<div class="empty-cart"><span>♡</span><b>Your basket is waiting</b><p>Add a few lovely things to get started.</p></div>';
    $('cartItems').querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.qty),q=cart[id]+Number(b.dataset.step);if(q<=0)delete cart[id];else if(q<=stock[id])cart[id]=q;else toast('That item is out of stock.');renderCart()});const t=totals();$('subtotal').textContent=money(t.subtotal);$('tax').textContent=money(t.tax);$('total').textContent=money(t.total);$('checkoutBtn').disabled=!entries.length;$('orderDate').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})
  }
  $('searchInput').addEventListener('input',renderProducts);$('clearCart').onclick=()=>{cart={};discount=0;renderCart()};$('discountButton').onclick=()=>{const code=prompt('Enter discount code');if(code&&code.trim().toUpperCase()==='LITTLELOVE'){discount=totals().subtotal*.1;renderCart();toast('10% little love discount applied!')}else if(code)toast('That code could not be found.')};$('filterButton').onclick=()=>{category=category==='All'?'Outfits':'All';renderCategories();renderProducts()};
  document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n===b));const page=b.dataset.page;$('posPage').hidden=page!=='pos';$('inventoryPage').hidden=page!=='inventory';$('ordersPage').hidden=page!=='orders';$('pageTitle').textContent=page==='pos'?'Point of sale':page==='inventory'?'Inventory':'Order history'});
  function renderInventory(){$('inventoryBody').innerHTML=PRODUCTS.map(p=>`<tr><td><b>${p.icon} &nbsp; ${p.name}</b></td><td>${p.category}</td><td>${money(p.price)}</td><td><span class="stock-chip">${stock[p.id]} in stock</span></td></tr>`).join('')}
  function renderOrders(){$('ordersBody').innerHTML=orders.length?orders.slice().reverse().map(o=>`<tr><td><b>${o.id}</b></td><td>${new Date(o.date).toLocaleDateString()}</td><td>${o.items} items</td><td><b>${money(o.total)}</b></td><td><span class="status-chip">${o.method} · Paid</span></td></tr>`).join(''):'<tr><td colspan="5" style="text-align:center;color:#97988f;padding:35px">No little moments here just yet.</td></tr>'}
  $('checkoutBtn').onclick=()=>{$('paymentTotal').textContent=money(totals().total);$('paymentModal').hidden=false};$('closePayment').onclick=()=>{$('paymentModal').hidden=true};document.querySelectorAll('.payment-method').forEach(b=>b.onclick=()=>{paymentMethod=b.dataset.method;document.querySelectorAll('.payment-method').forEach(x=>x.classList.toggle('chosen',x===b))});$('completePayment').onclick=()=>{const t=totals(),items=Object.values(cart).reduce((a,b)=>a+b,0);if(!items)return;for(const [id,q] of Object.entries(cart))stock[id]-=q;orders.push({id:'CB-'+Date.now().toString().slice(-7),date:new Date().toISOString(),items,total:t.total,method:paymentMethod});cart={};discount=0;persist();$('paymentModal').hidden=true;renderCart();renderProducts();renderInventory();renderOrders();toast('Sale complete. Thank you for shopping small!')};
  $('logoutBtn').onclick=()=>showAuth();
  const config={modelBasePath:'https://cdn.jsdelivr.net/npm/@vladmandic/human/models/',face:{enabled:true,detector:{enabled:true},mesh:{enabled:false},iris:{enabled:false},description:{enabled:true}},body:{enabled:false},hand:{enabled:false},object:{enabled:false},gesture:{enabled:false},filter:{enabled:false}};
  async function getHuman(){if(typeof Human==='undefined')throw new Error('The facial recognition service could not load. Check your internet connection.');if(!human){human=new Human.Human(config);await human.load()}return human}
  async function openCamera(mode){faceMode=mode;$('cameraModal').hidden=false;$('cameraError').textContent='';$('cameraTitle').textContent=mode==='enroll'?'Set up facial recognition':'Look into the camera';$('cameraHint').textContent=mode==='enroll'?'We will save a face profile on this device only.':'Center your face in the frame to continue.';$('captureFace').innerHTML=mode==='enroll'?'Save face profile <span>→</span>':'Continue <span>→</span>';$('cameraStatus').innerHTML='<span class="live-dot"></span> Starting camera…';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access requires HTTPS or localhost in a supported browser.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$('cameraVideo').srcObject=stream;await $('cameraVideo').play();$('cameraStatus').innerHTML='<span class="live-dot"></span> Camera ready'}catch(e){$('cameraError').textContent=e.message||'Please allow camera access to continue.';$('cameraStatus').textContent='Camera unavailable'}}
  function closeCamera(){$('cameraModal').hidden=true;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
  $('faceSignIn').onclick=()=>openCamera('login');$('closeCamera').onclick=closeCamera;$('cameraFallback').onclick=closeCamera;
  $('captureFace').onclick=async()=>{const button=$('captureFace'),video=$('cameraVideo');if(!stream){$('cameraError').textContent='Allow camera access, or use your password instead.';return}button.disabled=true;button.textContent='Looking for a match…';$('cameraError').textContent='';try{const h=await getHuman(),result=await h.detect(video),face=result.face?.[0];if(!face||!face.embedding?.length)throw new Error('We could not see a clear face. Adjust the light and try again.');const embedding=Array.from(face.embedding);
      if(faceMode==='enroll'){if(!currentUser)throw new Error('Sign in with your password first to set up face recognition.');users=users.map(u=>u.id===currentUser.id?{...u,faceEmbedding:embedding}:u);persist();toast('Facial recognition set up on this device.');closeCamera()}
      else{const matches=users.filter(u=>u.faceEmbedding?.length===embedding.length).map(u=>({u,distance:Math.sqrt(embedding.reduce((s,v,i)=>s+(v-u.faceEmbedding[i])**2,0))})).sort((a,b)=>a.distance-b.distance);if(!matches.length||matches[0].distance>0.6)throw new Error('No saved face profile matched. Sign in with your password or set up facial recognition.');closeCamera();showApp(matches[0].u);toast('Welcome back, '+(matches[0].u.name||'friend')+'!')}
    }catch(e){$('cameraError').textContent=e.message||'Facial recognition did not work. Please try again.'}finally{button.disabled=false;button.innerHTML=faceMode==='enroll'?'Save face profile <span>→</span>':'Continue <span>→</span>'}}
  function updateClock(){const now=new Date();$('clock').textContent=now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});$('todayDate').textContent=now.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});setTimeout(updateClock,60000)}
  $('year').textContent=new Date().getFullYear();setSignup(false);
})();
